---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nonprod-platform
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/myspotontheweb/gitops-platform-demo.git
      revision: HEAD
      directories:
      - path: addons/**/nonprod
  template:
    metadata:
      name: nonprod-platform-{{path[1]}}
    spec:
      project: "nonprod-platform"
      source:
        repoURL: https://github.com/myspotontheweb/gitops-platform-demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
