apiVersion: v2
name: ingress-nginx
description: Install the nginx ingress controller
type: application
version: 4.3.0
appVersion: "1.4.0"

dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.3.0
