---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'external-secrets-{{name}}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/myspotontheweb/gitops-platform-demo.git
        targetRevision: HEAD
        path: apps/external-secrets
      destination:
        name: '{{name}}'
        namespace: external-secrets
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
