apiVersion: v2
name: external-dns
description: Install external-dns
type: application
version: 6.10.2
appVersion: "0.12.2"

dependencies:
  - name: external-dns
    repository: https://charts.bitnami.com/bitnami
    version: 6.10.2
