apiVersion: v2
name: external-secrets
description: Install external-secrets
type: application
version: 0.6.0
appVersion: "v0.6.0"

dependencies:
  - name: external-secrets
    repository: https://charts.external-secrets.io
    version: 0.6.0
